In [1]:
import requests
from bs4 import BeautifulSoup

In [2]:
url="https://www.iplt20.com/auction"
res=requests.get(url)
print(res)

<Response [200]>

In [3]:
soup=BeautifulSoup(res.text,"html.parser")

In [5]:
year=soup.find('ul',class_="year-auction nav")
print(year)

<ul class="year-auction nav">
<li class="active"><a class="active show" href="https://www.iplt20.com/auction/2026">2026</a></li>
<li class=""><a class="" href="https://www.iplt20.com/auction/2025">2025</a></li>
<li class=""><a class="" href="https://www.iplt20.com/auction/2024">2024</a></li>
<li class=""><a class="" href="https://www.iplt20.com/auction/2023">2023</a></li>
<li class=""><a class="" href="https://www.iplt20.com/auction/2022">2022</a></li>
<li class=""><a class="" href="https://www.iplt20.com/auction/2021">2021</a></li>
<li class=""><a class="" href="https://www.iplt20.com/auction/2020">2020</a></li>
<li class=""><a class="" href="https://www.iplt20.com/auction/2019">2019</a></li>
<li class=""><a class="" href="https://www.iplt20.com/auction/2018">2018</a></li>
<li class=""><a class="" href="https://www.iplt20.com/auction/2017">2017</a></li>
<li class=""><a class="" href="https://www.iplt20.com/auction/2016">2016</a></li>
<li class=""><a class="" href="https://www.iplt20.com/auction/2015">2015</a></li>
<li class=""><a class="" href="https://www.iplt20.com/auction/2014">2014</a></li>
<li class=""><a class="" href="https://www.iplt20.com/auction/2013">2013</a></li>
</ul>

In [8]:
year.find_all("li")[7].text

'2019'

In [19]:
x=soup.find('table',class_="ih-td-tab w-100 auction-tbl")
rows=x.find_all("tr")
print(rows)

[<tr class="ih-pt-tbl" style="display:revert">
<th class="skip-filter" style="text-align: left;">Sr. No.</th>
<th class="skip-filter" style="text-align: left;">Team</th>
<th class="skip-filter">Funds Remaining</th>
<th class="skip-filter text-center">Overseas Players </th>
<th class="skip-filter text-center">Total Players</th>
</tr>, <tr>
<td class="ih-t-color">
<div class="ih-pt-ic">
<div class="ih-pt-img" style="width: 60px">
<img alt="" src="https://documents.iplt20.com/ipl/franchises/1764224441_1731684872_1702465555_CSKroundbig.png"/>
</div>
</div>
</td>
<td>₹2,40,00,000</td>
<td class="text-center">8</td>
<td class="text-center">25</td>
</tr>, <tr>
<td class="ih-t-color">
<div class="ih-pt-ic">
<div class="ih-pt-img" style="width: 60px">
<img alt="" src="https://documents.iplt20.com/ipl/franchises/1764224517_1731685245_1702465727_DCroundbig.png"/>
</div>
</div>
</td>
<td>₹35,00,000</td>
<td class="text-center">8</td>
<td class="text-center">25</td>
</tr>, <tr>
<td class="ih-t-color">
<div class="ih-pt-ic">
<div class="ih-pt-img" style="width: 60px">
<img alt="" src="https://documents.iplt20.com/ipl/franchises/1764224585_1731685262_1702465836_GTroundbig.png"/>
</div>
</div>
</td>
<td>₹1,95,00,000</td>
<td class="text-center">7</td>
<td class="text-center">25</td>
</tr>, <tr>
<td class="ih-t-color">
<div class="ih-pt-ic">
<div class="ih-pt-img" style="width: 60px">
<img alt="" src="https://documents.iplt20.com/ipl/franchises/1764224710_1731685297_1702465948_KKRroundbig.png"/>
</div>
</div>
</td>
<td>₹45,00,000</td>
<td class="text-center">8</td>
<td class="text-center">25</td>
</tr>, <tr>
<td class="ih-t-color">
<div class="ih-pt-ic">
<div class="ih-pt-img" style="width: 60px">
<img alt="" src="https://documents.iplt20.com/ipl/franchises/1764224788_1731684320_1702466030_LSGroundbig.png"/>
</div>
</div>
</td>
<td>₹4,55,00,000</td>
<td class="text-center">7</td>
<td class="text-center">25</td>
</tr>, <tr>
<td class="ih-t-color">
<div class="ih-pt-ic">
<div class="ih-pt-img" style="width: 60px">
<img alt="" src="https://documents.iplt20.com/ipl/franchises/1764224870_1731684308_1702466090_MIroundbig.png"/>
</div>
</div>
</td>
<td>₹55,00,000</td>
<td class="text-center">8</td>
<td class="text-center">25</td>
</tr>, <tr>
<td class="ih-t-color">
<div class="ih-pt-ic">
<div class="ih-pt-img" style="width: 60px">
<img alt="" src="https://documents.iplt20.com/ipl/franchises/1764224961_1731685190_1702466143_PBKSroundbig.png"/>
</div>
</div>
</td>
<td>₹3,50,00,000</td>
<td class="text-center">8</td>
<td class="text-center">25</td>
</tr>, <tr>
<td class="ih-t-color">
<div class="ih-pt-ic">
<div class="ih-pt-img" style="width: 60px">
<img alt="" src="https://documents.iplt20.com/ipl/franchises/1764225018_1743157275_RRroundbig.png"/>
</div>
</div>
</td>
<td>₹2,65,00,000</td>
<td class="text-center">8</td>
<td class="text-center">25</td>
</tr>, <tr>
<td class="ih-t-color">
<div class="ih-pt-ic">
<div class="ih-pt-img" style="width: 60px">
<img alt="" src="https://documents.iplt20.com/ipl/franchises/1764225174_1731684948_1702466217_RCBroundbig.png"/>
</div>
</div>
</td>
<td>₹25,00,000</td>
<td class="text-center">8</td>
<td class="text-center">25</td>
</tr>, <tr>
<td class="ih-t-color">
<div class="ih-pt-ic">
<div class="ih-pt-img" style="width: 60px">
<img alt="" src="https://documents.iplt20.com/ipl/franchises/1764225435_1731685022_1702466366_SRHroundbig.png"/>
</div>
</div>
</td>
<td>₹5,45,00,000</td>
<td class="text-center">8</td>
<td class="text-center">25</td>
</tr>]

In [20]:
columns=[i.text.strip() for i in rows[0].find_all('th')[2:]]
print(columns)

['Funds Remaining', 'Overseas Players', 'Total Players']

In [31]:
data=[]
for i in rows[1:]:
    data.append([j.text.strip() for j in i.find_all('td')[1:]])
print(data)

[['₹2,40,00,000', '8', '25'], ['₹35,00,000', '8', '25'], ['₹1,95,00,000', '7', '25'], ['₹45,00,000', '8', '25'], ['₹4,55,00,000', '7', '25'], ['₹55,00,000', '8', '25'], ['₹3,50,00,000', '8', '25'], ['₹2,65,00,000', '8', '25'], ['₹25,00,000', '8', '25'], ['₹5,45,00,000', '8', '25']]

In [33]:
import pandas as pd
df=pd.DataFrame(data=data,columns=columns)
df

  Funds Remaining Overseas Players Total Players
0    ₹2,40,00,000                8            25
1      ₹35,00,000                8            25
2    ₹1,95,00,000                7            25
3      ₹45,00,000                8            25
4    ₹4,55,00,000                7            25
5      ₹55,00,000                8            25
6    ₹3,50,00,000                8            25
7    ₹2,65,00,000                8            25
8      ₹25,00,000                8            25
9    ₹5,45,00,000                8            25

In [62]:
base_url="https://books.toscrape.com/catalogue/page-{}.html"
titles=[]
prices=[]
ratings=[]
for page in range(1,6):
    url=base_url.format(page)
   # print(url)
    
    res=requests.get(url)
   # print(res)

    soup=BeautifulSoup(res.text,"html.parser")
   # print(soup)
    books=soup.find_all('article',class_="product_pod")
   # print(books)
    for book in books:
        title=book.h3.a['title']
        titles.append(title)

        price=book.find('p',class_="price_color").text
        prices.append(price)
        # print(price)

        rating=book.p['class'][1]
        ratings.append(rating)
        # print(rating)
print(titles)

['A Light in the Attic', 'Tipping the Velvet', 'Soumission', 'Sharp Objects', 'Sapiens: A Brief History of Humankind', 'The Requiem Red', 'The Dirty Little Secrets of Getting Your Dream Job', 'The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull', 'The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics', 'The Black Maria', 'Starving Hearts (Triangular Trade Trilogy, #1)', "Shakespeare's Sonnets", 'Set Me Free', "Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)", 'Rip it Up and Start Again', 'Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991', 'Olio', 'Mesaerion: The Best Science Fiction Stories 1800-1849', 'Libertarianism for Beginners', "It's Only the Himalayas", 'In Her Wake', 'How Music Works', 'Foolproof Preserving: A Guide to Small Batch Jams, Jellies, Pickles, Condiments, and More: A Foolproof Guide to Making Small Batch Jams, Jellies, Pickles, Condiments, and More', 'Chase Me (Paris Nights #2)', 'Black Dust', 'Birdsong: A Story in Pictures', "America's Cradle of Quarterbacks: Western Pennsylvania's Football Factory from Johnny Unitas to Joe Montana", 'Aladdin and His Wonderful Lamp', 'Worlds Elsewhere: Journeys Around Shakespeareâ\x80\x99s Globe', 'Wall and Piece', 'The Four Agreements: A Practical Guide to Personal Freedom', 'The Five Love Languages: How to Express Heartfelt Commitment to Your Mate', 'The Elephant Tree', 'The Bear and the Piano', "Sophie's World", 'Penny Maybe', 'Maude (1883-1993):She Grew Up with the country', 'In a Dark, Dark Wood', 'Behind Closed Doors', "You can't bury them all: Poems", 'Slow States of Collapse: Poems', 'Reasons to Stay Alive', 'Private Paris (Private #10)', '#HigherSelfie: Wake Up Your Life. Free Your Soul. Find Your Tribe.', 'Without Borders (Wanderlove #1)', 'When We Collided', 'We Love You, Charlie Freeman', 'Untitled Collection: Sabbath Poems 2014', 'Unseen City: The Majesty of Pigeons, the Discreet Charm of Snails & Other Wonders of the Urban Wilderness', 'Unicorn Tracks', 'Unbound: How Eight Technologies Made Us Human, Transformed Society, and Brought Our World to the Brink', 'Tsubasa: WoRLD CHRoNiCLE 2 (Tsubasa WoRLD CHRoNiCLE #2)', 'Throwing Rocks at the Google Bus: How Growth Became the Enemy of Prosperity', 'This One Summer', 'Thirst', 'The Torch Is Passed: A Harding Family Story', 'The Secret of Dreadwillow Carse', 'The Pioneer Woman Cooks: Dinnertime: Comfort Classics, Freezer Food, 16-Minute Meals, and Other Delicious Ways to Solve Supper!', 'The Past Never Ends', 'The Natural History of Us (The Fine Art of Pretending #2)', 'The Nameless City (The Nameless City #1)', 'The Murder That Never Was (Forensic Instincts #5)', "The Most Perfect Thing: Inside (and Outside) a Bird's Egg", 'The Mindfulness and Acceptance Workbook for Anxiety: A Guide to Breaking Free from Anxiety, Phobias, and Worry Using Acceptance and Commitment Therapy', 'The Life-Changing Magic of Tidying Up: The Japanese Art of Decluttering and Organizing', 'The Inefficiency Assassin: Time Management Tactics for Working Smarter, Not Longer', 'The Gutsy Girl: Escapades for Your Life of Epic Adventure', 'The Electric Pencil: Drawings from Inside State Hospital No. 3', 'The Death of Humanity: and the Case for Life', 'The Bulletproof Diet: Lose up to a Pound a Day, Reclaim Energy and Focus, Upgrade Your Life', 'The Art Forger', 'The Age of Genius: The Seventeenth Century and the Birth of the Modern Mind', "The Activist's Tao Te Ching: Ancient Advice for a Modern Revolution", 'Spark Joy: An Illustrated Master Class on the Art of Organizing and Tidying Up', 'Soul Reader', 'Security', 'Saga, Volume 6 (Saga (Collected Editions) #6)', 'Saga, Volume 5 (Saga (Collected Editions) #5)', 'Reskilling America: Learning to Labor in the Twenty-First Century', 'Rat Queens, Vol. 3: Demons (Rat Queens (Collected Editions) #11-15)', 'Princess Jellyfish 2-in-1 Omnibus, Vol. 01 (Princess Jellyfish 2-in-1 Omnibus #1)', 'Princess Between Worlds (Wide-Awake Princess #5)', 'Pop Gun War, Volume 1: Gift', 'Political Suicide: Missteps, Peccadilloes, Bad Calls, Backroom Hijinx, Sordid Pasts, Rotten Breaks, and Just Plain Dumb Mistakes in the Annals of American Politics', 'Patience', 'Outcast, Vol. 1: A Darkness Surrounds Him (Outcast #1)', 'orange: The Complete Collection 1 (orange: The Complete Collection #1)', 'Online Marketing for Busy Authors: A Step-By-Step Guide', 'On a Midnight Clear', 'Obsidian (Lux #1)', 'My Paris Kitchen: Recipes and Stories', 'Masks and Shadows', 'Mama Tried: Traditional Italian Cooking for the Screwed, Crude, Vegan, and Tattooed', 'Lumberjanes, Vol. 2: Friendship to the Max (Lumberjanes #5-8)', 'Lumberjanes, Vol. 1: Beware the Kitten Holy (Lumberjanes #1-4)', 'Lumberjanes Vol. 3: A Terrible Plan (Lumberjanes #9-12)', 'Layered: Baking, Building, and Styling Spectacular Cakes', 'Judo: Seven Steps to Black Belt (an Introductory Guide for Beginners)', 'Join', 'In the Country We Love: My Family Divided']

In [63]:
df=pd.DataFrame({'book_title':titles,
                'book_price':price,
                'book_rating':ratings})
df

                                           book_title book_price book_rating
0                                A Light in the Attic    Â£22.00       Three
1                                  Tipping the Velvet    Â£22.00         One
2                                          Soumission    Â£22.00         One
3                                       Sharp Objects    Â£22.00        Four
4               Sapiens: A Brief History of Humankind    Â£22.00        Five
..                                                ...        ...         ...
95  Lumberjanes Vol. 3: A Terrible Plan (Lumberjan...    Â£22.00         Two
96  Layered: Baking, Building, and Styling Spectac...    Â£22.00         One
97  Judo: Seven Steps to Black Belt (an Introducto...    Â£22.00         Two
98                                               Join    Â£22.00        Five
99          In the Country We Love: My Family Divided    Â£22.00        Four

[100 rows x 3 columns]

In [ ]:
url="https://subslikescript.com/movies?page="